<?php
/**
 * Created by PhpStorm.
 * User: michal
 * Date: 19.11.18
 * Time: 10:27
 *
 * @var $product_object WC_Product
 */

?>
<div class="options_group show_if_meters">
<?php
	woocommerce_wp_text_input(
		array(
			'id'          => '_meters_in_box',
			'value'       => $product_object->get_meta( '_meters_in_box' ),
			'data_type'   => 'decimal',
			'label'       => __( 'Ilość m<sup>2</sup> w opakowaniu', 'elazienki' ),
		)
	);

	woocommerce_wp_text_input(
		array(
			'id'          => '_items_in_box',
			'value'       => $product_object->get_meta( '_items_in_box' ),
			'data_type'   => 'decimal',
			'label'       => __( 'Ilośc sztuk w opakowaniu', 'elazienki' ),
		)
	);

?>
</div>

